name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_DB_USERNAME: root
  APP_DB_PASSWORD: secret
  APP_DB_NAME: simple_bank

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  steps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.14.x

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
